"""empty message

Revision ID: 847d4a6e313d
Revises: 67f4449e56ab
Create Date: 2023-12-02 02:05:14.141243-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "847d4a6e313d"
down_revision = "67f4449e56ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_author_id"), "author", ["id"], unique=False)
    op.create_index(op.f("ix_book_id"), "book", ["id"], unique=False)
    op.create_index(op.f("ix_review_id"), "review", ["id"], unique=False)
    op.alter_column("user", "is_superuser", existing_type=sa.BOOLEAN(), nullable=True)
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.alter_column("user", "is_superuser", existing_type=sa.BOOLEAN(), nullable=False)
    op.drop_index(op.f("ix_review_id"), table_name="review")
    op.drop_index(op.f("ix_book_id"), table_name="book")
    op.drop_index(op.f("ix_author_id"), table_name="author")
    # ### end Alembic commands ###
