"""add review hour

Revision ID: ffe73ac93180
Revises: adf554bad482
Create Date: 2023-12-02 10:45:11.866024-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ffe73ac93180"
down_revision = "adf554bad482"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    op.add_column(
        "book",
        sa.Column(
            "review_hour_amount",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )
    op.add_column(
        "review",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review", "created_at")
    op.drop_column("book", "review_hour_amount")
    op.drop_column("book", "created_at")
    # ### end Alembic commands ###
